### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by simrat39** [simrat39/AnimeTwistFlut#1]
* [x]  Remember last seen anime + episode and show it on the homepage.

* [x]  Make landscape look good.

* [ ]  Cleanup watch page code and segregate things a bit.

* [x]  Cleanup imports.

* [x]  Support chat viewing

* [x] Handle failed network requests

* [x] Cache main anime data every 3 days

* [ ] ~~Support logging in and sending messages~~

* [x] Bring back landscape but support the in app rotate button 

* [x] Allow hiding MOTD 

* [x] Fix anime info page's list view 

* [x] Improve watch page padding

* [x] Allow launching mal link from anime info page

* [x] Allow setting episodes as completed / store that data like the website

* [ ] Cleanup ScrollController / TextEditingController shenanigans

* [x] Add slight delay to animeinfopage loading if all data is provided

* [x] Handle kitsu id being null

* [x] Show donation methods directly in the app

* [x] Fix boku no plco not running

* [x] Parse greater than 1 hour times correctly

* [x] Add a decent icon

* [x] Make a decent splash screen

* [x] Basic picture in picture support

* [] Fix recently watched ep text size

* [] Set ep as completed if ep is finished or if user goes to next ep
